In [65]:
# Application Study

import torch as torch
#from models.MVCNN import SVCNN, MVCNN
from models.MVCNN_application import SVCNN, MVCNN

path_to_stage1_models = r"mvcnn_stage_1/"
load_model = "model-00029.pth"
sv_model = SVCNN(cnn_name="vgg11", name="mvcnn")

sv_model.load(path_to_stage1_models, modelfile=load_model)

path_to_stage2_models = r"mvcnn_stage_2/mvcnn/"
load_model2 = "model-00026.pth"

model2 = torch.load(path_to_stage2_models+load_model2)

mv_model = MVCNN(name = "mvcnn", model = sv_model, nclasses=3, cnn_name="vgg11")  # create an instance of the model
mv_model.load(r"mvcnn_stage_2/", modelfile=load_model2)

mv_model.eval()



MVCNN(
  (net_1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (11): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (14): ReLU(inplace=True)
    (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  

In [69]:


from tools.ImgDataset_application import *

val_path ='test_samples/fold'



In [70]:
filepaths = []

num_views = 3

all_files = sorted(glob.glob(val_path+'/'+'*.png'))
print(all_files)
stride = int(3/num_views)
all_files = all_files[::stride]

transform = transforms.Compose([
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])
            ])

filepaths.extend(all_files[:3])


print(int(len(filepaths)/num_views))

['test_samples/fold/Obj_16001_v01.png', 'test_samples/fold/Obj_16001_v02.png', 'test_samples/fold/Obj_16001_v03.png']
1


In [71]:
filepaths[0]

'test_samples/fold/Obj_16001_v01.png'

In [72]:
# load images 

im_1 = Image.open(filepaths[0]).convert('RGB')
print(type(im_1))
im_2 = Image.open(filepaths[1]).convert('RGB')
im_3 = Image.open(filepaths[2]).convert('RGB')


import torchvision.transforms as T

transformt = T.ToPILImage()

imgs = []
img_1 = transformt(transform(im_1))
imgs.append(img_1)
img_2 = transformt(transform(im_2))
imgs.append(img_2)
img_3 = transformt(transform(im_3))
imgs.append(img_3)

print(type(imgs))
imgs


<class 'PIL.Image.Image'>
<class 'list'>


[<PIL.Image.Image image mode=RGB size=232x231 at 0x7F65AD96DA30>,
 <PIL.Image.Image image mode=RGB size=232x231 at 0x7F65ADE3C910>,
 <PIL.Image.Image image mode=RGB size=232x231 at 0x7F65ADE3C940>]

In [73]:


from torchvision import transforms as transforms



transform=transforms.ToTensor()
img_tensor_1 = transform(imgs[0])
img_tensor_2 = transform(imgs[1])
img_tensor_3 = transform(imgs[2])

ims_stack = torch.stack([img_tensor_1, img_tensor_2, img_tensor_3], dim=1)

print(type(ims_stack))
print(len(ims_stack))
print(ims_stack.size())
ims_stack[2]

<class 'torch.Tensor'>
3
torch.Size([3, 3, 231, 232])


tensor([[[0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         ...,
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451]],

        [[0.4196, 0.4196, 0.4196,  ..., 0.6314, 0.6314, 0.6314],
         [0.4196, 0.4196, 0.4196,  ..., 0.6314, 0.6314, 0.6314],
         [0.4196, 0.4196, 0.4196,  ..., 0.6314, 0.6314, 0.6314],
         ...,
         [0.2039, 0.2039, 0.2039,  ..., 0.1765, 0.1765, 0.1765],
         [0.2039, 0.2039, 0.2039,  ..., 0.1765, 0.1765, 0.1765],
         [0.2039, 0.2039, 0.2039,  ..., 0.1765, 0.1765, 0.1765]],

        [[0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.7451],
         [0.7451, 0.7451, 0.7451,  ..., 0.7451, 0.7451, 0.

In [74]:
val_loader_mi = torch.utils.data.DataLoader(ims_stack.unsqueeze(dim=0), batch_size=1, shuffle=False, num_workers=0)
print(len(val_loader_mi))

1


In [75]:
from torch.autograd import Variable

#data = val_loader_mi
for i, data in (enumerate(val_loader_mi, 0)):
    print(i)
    print(data.size())
    N,V,C,H,W = data.size()
    in_data = Variable(data).view(-1,C,H,W)
    #print(in_data)
    with torch.inference_mode():
        out_data = mv_model(in_data)
        print(out_data)
        pred_prob = torch.softmax(out_data.squeeze(), dim=0)
        print(pred_prob)
        pred = torch.max(out_data, 1)[1]
        print(pred)

0
torch.Size([1, 3, 3, 231, 232])
tensor([[-1.6668,  4.0951, -4.7458]])
tensor([3.1347e-03, 9.9672e-01, 1.4422e-04])
tensor([1])


In [76]:
val_loader_si = torch.utils.data.DataLoader(img_tensor_3.unsqueeze(dim=0), batch_size=1, shuffle=False, num_workers=0)
print(len(val_loader_si))

1


In [77]:
from torch.autograd import Variable


for i, datas in enumerate(val_loader_si, 0):
    in_data = Variable(datas)
    with torch.inference_mode():
        out_datas = sv_model(in_data)
        print(out_datas)
        pred_probs = torch.softmax(out_datas.squeeze(), dim=0)
        print(pred_probs)
        preds = torch.max(out_datas, 1)[1]
        print(preds)
    
    

tensor([[ 0.2543,  1.0403, -2.7957]])
tensor([0.3085, 0.6769, 0.0146])
tensor([1])
